# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./backend/FlagExplorerBackend.sln
      
    - name: Build
      run: dotnet build ./backend/FlagExplorerBackend.sln --no-restore
      
    - name: Run Unit Tests
      run: dotnet test ./backend/Tests/FlagExplorerBackend.Tests/ --logger "junit;LogFilePath=test-results.xml"
      
    - name: Run Integration Tests
      run: dotnet test ./backend/Tests/FlagExplorerBackend.Tests.Integration/ --logger "junit;LogFilePath=test-results.xml"

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      with:
        name: .NET Test Results
        path: test-results.xml
        reporter: java-junit
